### ISSUE TITLE
Can I get banned using this?

### ISSUE THREAD

**Issue by fgsfds1** [amylase/kancolle-auto#7]
Do you have any information on users banned by DMM while using this tool?

**Comment by ghost** [comment]
If you don't want to face the risk, just don't use this tool.

2015/04/04 $B8a8e(B2:40$B!"(B"Sergey Sofeychuk" notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by fgsfds1** [comment]
You're right, I'll close this issue then.
